export const menuItems = [
  { name: 'Cluster', types: [1], inputType: 'text' },
  { name: 'Slot', types: [1], inputType: 'text' },
  { name: 'Channel', types: [1], inputType: 'text' },
  { name: 'Type', types: [2], inputType: 'text' },
  { name: 'LinearizationType', types: [2], inputType: 'text' },
  { name: 'CustomLinName', types: [2], inputType: 'text' },
  { name: 'TemperatureUnit', types: [2], inputType: 'text' },
  { name: 'PVOffset', types: [2], inputType: 'number', min: 0, max: 100 },
  { name: 'PVRangeHigh', types: [2], inputType: 'number', min: 0, max: 100 },
  { name: 'PVRangeLow', types: [2], inputType: 'number', min: 0, max: 100 },
  { name: 'InputHigh', types: [2], inputType: 'number', min: 0, max: 100 },
  { name: 'InputLow', types: [2], inputType: 'number', min: 0, max: 100 },
  { name: 'ClipEnable', types: [2], inputType: 'checkbox' },
  { name: 'ClipPercentage', types: [2], inputType: 'number', min: 0, max: 100 },
  { name: 'SensorBreakDelay', types: [2], inputType: 'number', min: 0, max: 100 },
  { name: 'Emissivity', types: [2], inputType: 'number', min: 0, max: 100 },
  { name: 'ShuntValue', types: [2], inputType: 'number', min: 0, max: 100 },
  { name: 'FilterTime', types: [2], inputType: 'number', min: 0, max: 100 },
  { name: 'PVBadAction', types: [2], inputType: 'text' },
  { name: 'SensorBreakDetection', types: [2], inputType: 'checkbox' },
  { name: 'SensorBreakAction', types: [2], inputType: 'text' },
  { name: 'PV', types: [3], inputType: 'number', min: 0, max: 100 },
  { name: 'PVStatus', types: [3], inputType: 'text' },
  { name: 'MeasuredValue', types: [3], inputType: 'number', min: 0, max: 100 },
  { name: 'MeasuredValueStatus', types: [3], inputType: 'text' },
  { name: 'LeadResistance', types: [3], inputType: 'number', min: 0, max: 100 },
  { name: 'SensorBreakPercentage', types: [3], inputType: 'number', min: 0, max: 100 },
  { name: 'ApplyResistor', types: [3], inputType: 'checkbox' },
  { name: 'CJCType', types: [4], inputType: 'text' },
  { name: 'CJRemoteTemperature', types: [4], inputType: 'number', min: 0, max: 100 },
  { name: 'CJRemoteTemperatureStatus', types: [4], inputType: 'text' },
  { name: 'CJAutoTemperature', types: [4], inputType: 'number', min: 0, max: 100 },
  { name: 'CJFixedTemperature', types: [4], inputType: 'number', min: 0, max: 100 },
  { name: 'UserCalibrationMode', types: [5], inputType: 'text' },
  { name: 'UserCalMeasuredPoint', types: [5], inputType: 'number', min: 0, max: 100 },
  { name: 'UserCalTargetedPoint', types: [5], inputType: 'number', min: 0, max: 100 },
  { name: 'UserCalPoints', types: [5], inputType: 'number', min: 0, max: 100 },
  { name: 'CalibrationSelection', types: [5], inputType: 'text' },
  { name: 'UserCalLast', types: [5], inputType: 'text' },
  { name: 'UserCalMeasuredPointStored', types: [5], inputType: 'number', min: 0, max: 100 },
  { name: 'UserCalTargetedPointStored', types: [5], inputType: 'number', min: 0, max: 100 }
];
